# Generated by Django 5.1.2 on 2024-10-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ETFHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etf_ticker', models.CharField(max_length=10)),
                ('stock_symbol', models.CharField(max_length=10)),
                ('holding_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('stock_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateField(auto_now=True)),
            ],
        ),
    ]
