# Generated by Django 5.1.2 on 2024-10-25 17:08

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_etfholding_holding_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etfholding',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='etfholding',
            name='stock_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='etfholding',
            unique_together={('etf_ticker', 'stock_symbol')},
        ),
    ]
