# Generated by Django 5.1.2 on 2024-10-25 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_etfholding_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='etfholding',
            old_name='stock_price',
            new_name='etf_price',
        ),
    ]
