# Generated by Django 5.1.2 on 2024-10-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account_balance',
            new_name='available_cash',
        ),
    ]
