# Generated by Django 5.1.2 on 2024-10-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_stocktransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocktransaction',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='userstock',
            name='stock_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
    ]
